version: '3.12'

services:
  app:
    image: django_template:app
    build:
      context: .
    env_file:
      - .env
    restart: no
    stdin_open: true
    command: >
      sh -c "
            python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "0.0.0.0:9005:8000"
    tty: true
    volumes:
      - .:/django_app